import "./globals.css";
import { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query";
import { trpc } from "./_trpc/trpc";
import Provider from "./_trpc/Provider";
import Navbar from "@/Components/Navbar";
import Script from "next/script";
import Username from "@/Components/Username";
import Wrapper from "@/Components/Wrapper";

export const metadata = {
	title: "Next Client",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<Script src="https://accounts.google.com/gsi/client" async defer />
			<body className="max-w-full min-h-screen">
				<Provider>
					<Wrapper>{children}</Wrapper>
				</Provider>
			</body>
		</html>
	);
}
